### ISSUE TITLE
Extra parameters on OnException

### ISSUE THREAD

**Issue by valdetero** [Fody/MethodDecorator#16]
Why is there a parameter count check in ModuleWeaver? I would like to add extra parameters to the OnException method but I can't. If this isn't acceptable, maybe you could add the extra parameters in the code itself?

Is there anyway to have these parameters on the OnException method?
[CallerMemberName] string memberName = "", [CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0

Or at least the latter two (since member name is already obtained)?

**Comment by alexeysuvorov** [comment]
Hello, the reason why we checking for parameters count is because generated IL expects predefined count of parameters. 
You can find line number and source file name in exception stack trace if it is available. I don't think we can provide more info than exception instance itself. As you already noted you already have member name.

**Comment by SimonCropp** [comment]
seems this is answered so closing
