### ISSUE TITLE
CA1062 Errors

### ISSUE THREAD

**Issue by dalealleshouse** [Fody/MethodDecorator#18]
I originally submitted this issue to the Fody project: https://github.com/Fody/Fody/issues/163. However, it seems to be an issue with this plug in.

Including MethodDecorator in a project causes code analysis to raise false positive errors. Specifically CA1062: Validate arguments of public methods.

See the following repo that demonstrates the error: https://github.com/dalealleshouse/FodyExample.

Thank you very much for your time!

**Comment by SimonCropp** [comment]
@dalealleshouse looks lik no one else is interested in fixing this. so guessing if you want it fixed you will need to send a PR

**Comment by buddde** [comment]
I have the same issue too. Can you please consider reopeing it? Thank you.

I once helped myself (before Fody, just PropertyChanged as far as I remember) by changing two values in the Fody.targets, but this does not seem to work anymore (xpath-like syntax):
/Project/Target/AfterTargets=AfterBuild (instead of afterCompile)
/Project/Target/Fody.WeavingTask/AssemblyPath="$(TargetPath)" (instead of "@(IntermediateAssembly)")

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
